{% set name = "flake8-noqa" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-noqa-{{ version }}.tar.gz
  sha256: 771765ab27d1efd157528379acd15131147f9ae578a72d17fb432ca197881243

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - flake8 >=3.8.0,<8.0
    - typing-extensions >=3.7.4.2
    - importlib-metadata <5.0.0,>=4.0.0

test:
  imports:
    - flake8_noqa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flake8-noqa/
  dev_url: https://github.com/plinss/flake8-noqa/
  summary: Flake8 noqa comment validation
  license: LGPL-3.0-only
  license_file:
    - COPYING.LESSER
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
