{% set name = "flake8-noqa" %}
{% set version = "1.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-noqa-{{ version }}.tar.gz
  sha256: 435061949c2dc633d34536bfae3c2a3cc45fa6cdb87bd6c6a25c974f415297fa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flake8 >=3.8.0,<5.0
    - python >=3.6
    - typing-extensions <5.0,>=3.7.4.2

test:
  imports:
    - flake8_noqa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/plinss/flake8-noqa/
  summary: Flake8 noqa comment validation
  license: LGPL-3.0-only
  license_file:
    - COPYING.LESSER
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
